from main import Chatbot
import streamlit as st

bot = Chatbot()

st.set_page_config(page_title = "Literature Bot")
with st.sidebar:
    st.title('Literature Bot')

# Generate LLM response
def generate_response(input):
    result = bot.rag_chain.invoke(input)
    return result

# Store responses generated by LLM
if "messages" not in st.session_state.keys():
    st.session_state.messages = [{"role": "assistant", "content": "Hello, let's talk about your favourite poem"}]

# Display chat messages
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.write(message["content"])

# User-provided prompt
if input := st.chat_input():
    st.session_state.messages.append({"role": "user", "content": input})
    with st.chat_message("user"):
        st.write(input)

# Generate a new response if last message is not from assistant
if st.session_state.messages[-1]["role"] != "assistant":
    with st.chat_message("assistant"):
        with st.spinner("Hmmm..."):
            response = generate_response(input) 
            st.write(response) 
    message = {"role": "assistant", "content": response}
    st.session_state.messages.append(message)